In [1]:
import numpy as np

In [2]:
mylist=[1,2,3]

In [3]:
arr=np.array(mylist)
arr

array([1, 2, 3])

In [4]:
wrong_matrix=[ [1, 2, 3], [4,5,6],[7,8,9]] #it is not a matrix
wrong_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(wrong_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,20,5)

array([ 0,  5, 10, 15])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
np.ones((3,3)) # 2 dimension

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.linspace(0,5,10) #1 dimension 10 is the number of points

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.randn(2) # it gives a random number between -1 and 1

array([-0.19771068, -2.03840095])

In [18]:
np.random.randn(3,3)

array([[-1.0581831 ,  1.19347904,  1.24415972],
       [-1.35575093, -1.29257786, -0.85672735],
       [ 0.13804014,  0.24305961,  0.15687687]])

In [19]:
np.random.randint(1,100) #See it is differnet than random.randn it gives a random INTEGER number

22

In [20]:
np.random.randint(1,100,12)

array([69, 69, 72, 45, 25, 56, 70,  9, 43,  3, 41,  9])

In [21]:
np.random.randint(1,100, (2,2))

array([[71, 14],
       [50, 36]])

In [23]:
arr=np.arange(25)
ranarr=np.random.randint(0,50,10)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
ranarr

array([27,  7, 32, 49, 40, 29, 14, 16,  5, 18])

In [26]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
arr #even though its shape is changed it still what it is at the beginning

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranarr

array([27,  7, 32, 49, 40, 29, 14, 16,  5, 18])

In [29]:
ranarr.max()

49

In [30]:
ranarr.argmax()

3

In [31]:
ranarr.sort()

In [32]:
ranarr #reshape vs sort.

array([ 5,  7, 14, 16, 18, 27, 29, 32, 40, 49])

In [33]:
# Vector no dimension if (x, )
arr.shape

(25,)

In [34]:
#Notice the two sets of brackets
arr.reshape(1,25)  #[[]] first inside we have one element when we enter second [ ] there are 25 elements#

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [35]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

#**Numpy indexing and selection**

In [38]:
a=np.arange(11)

In [39]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
a[8]

8

In [41]:
a[1:5]

array([1, 2, 3, 4])

In [42]:
a[:6]

array([0, 1, 2, 3, 4, 5])

In [43]:
a[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
#Setting a value with index range (Broadcasting)
a[0:3]=15
a

array([15, 15, 15,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
# Reset array
a = np.arange(11)
#Show
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
# Slices
slice_of_a = a[0:6]
#Show slice
slice_of_a

array([0, 1, 2, 3, 4, 5])

In [47]:
#Change Slice
slice_of_a[:]=99
#Show Slice again
slice_of_a

array([99, 99, 99, 99, 99, 99])

In [48]:
#Now note the changes also occur in our original array!
a

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [49]:
#Data is not copied, it's a view of the original array! This avoids memory problems!
#To get a copy, need to be explicit
a_copy = a.copy()
a_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [51]:
a_copy[:]=100
a_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [52]:
a

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [53]:
a_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
a_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [55]:
a_2d[2][2]

45

In [56]:
a_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [57]:
#Shape bottom row
a_2d[2,:]

array([35, 40, 45])

In [58]:
b=np.arange(1,11)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
#short way
b[b>5]

array([ 6,  7,  8,  9, 10])

In [60]:
c_2d=np.arange(0,50).reshape(5,10)
c_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [61]:
c_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

#**Numpy Operations**

In [62]:
arr = np.arange(10)
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [63]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [64]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

<ipython-input-64-2f119c028196>:3: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [65]:
# Also warning, but not an error instead infinity
1/arr

<ipython-input-65-c81c9b6169c9>:2: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [66]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [67]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [68]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [69]:
np.max(arr) #same as arr.max()

9

In [70]:
np.log(arr)

<ipython-input-70-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [71]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [72]:
#Use NumPy to generate a random number between 0 and 1
np.random.rand(1)

array([0.83499643])

In [73]:
#Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
np.random.randn(25)

array([-1.1420843 ,  0.58127084, -1.44405571,  2.06601322,  0.03417302,
        1.0173592 ,  1.57318069,  1.34658025, -0.75337798, -0.05228945,
       -0.02152507,  0.21694589,  0.89589256,  1.47826844,  2.35554022,
       -1.38974104,  2.17306777, -0.05460348, -1.30647793, -1.21503956,
        2.59678859, -0.32102241, -0.42818557,  0.26692105,  0.98046568])

In [74]:
np.arange(1,101).reshape(10,10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [75]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [76]:
mat = np.arange(1,26).reshape(5,5)
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [77]:
mat[3,4]

20

In [78]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [79]:
#sum of all values.
np.sum(mat[:])

325

In [80]:
np.std(mat[:])

7.211102550927978

In [81]:
#the sum of all the columns in mat
mat.sum(axis=0)

array([55, 60, 65, 70, 75])